<script lang="ts">
	import Breadcrumb from '$lib/components/Breadcrumb.svelte';
	import TableOfContents from '$lib/components/TableOfContents.svelte';
	import PrevNextNav from '$lib/components/PrevNextNav.svelte';
	import RelatedContent from '$lib/components/RelatedContent.svelte';
	import { getDocNav } from '$lib/navigation.js';
	import type { RelatedLink } from '$lib/navigation.js';
	import { jsonLdScript, graph, breadcrumbList, techArticle } from '$lib/seo.js';

	const { prev, next } = getDocNav('introduction');

	const tocItems = [
		{ id: 'what-it-is', label: 'What it is' },
		{ id: 'problem', label: 'The problem with static secrets' },
		{ id: 'how-different', label: 'How amesh is different' },
		{ id: 'philosophy', label: 'Design philosophy' },
		{ id: 'not-for', label: 'What amesh is not for' },
	];

	const relatedLinks: RelatedLink[] = [
		{ href: '/docs/quickstart', title: 'Quickstart', desc: 'Install, pair, and sign your first request', type: 'doc' },
		{ href: '/docs/integration', title: 'Integration Guide', desc: 'Express, microservices, webhooks', type: 'doc' },
	];
</script>

<svelte:head>
	<title>What is amesh — Introduction</title>
	<meta name="description" content="amesh replaces static API keys with device-bound cryptographic identity. Private keys stay on the device, protected by Secure Enclave, TPM, or encrypted file." />
	<link rel="canonical" href="https://authmesh.dev/docs/introduction" />
	<meta property="og:title" content="What is amesh — Introduction" />
	<meta property="og:description" content="Device-bound M2M authentication. Replace static API keys with cryptographic device identity." />
	<meta property="og:url" content="https://authmesh.dev/docs/introduction" />
	{@html jsonLdScript(graph(
		breadcrumbList([
			{ name: 'Home', url: '/' },
			{ name: 'Docs', url: '/docs' },
			{ name: 'Introduction', url: '/docs/introduction' }
		]),
		techArticle({
			title: 'What is amesh — Introduction',
			description: 'Device-bound M2M authentication explained. Replace static API keys with cryptographic device identity.',
			url: '/docs/introduction',
			section: 'Introduction'
		})
	))}
</svelte:head>

<div class="mx-auto max-w-2xl px-6 pb-20">
	<section class="pt-16 pb-6">
		<Breadcrumb crumbs={[{ label: 'Docs', href: '/docs' }, { label: 'Introduction' }]} />
		<h1 class="mt-4 text-3xl font-bold text-zinc-50">What is amesh</h1>
		<p class="mt-3 text-lg text-zinc-400">Device-bound machine-to-machine authentication. No static secrets, no rotation, no leaks.</p>
		<TableOfContents items={tocItems} />
	</section>

	<section class="py-8">
		<h2 id="what-it-is" class="scroll-mt-20 text-xl font-semibold text-zinc-50">What it is</h2>
		<p class="mt-3 text-zinc-400">
			amesh is a drop-in replacement for API keys, Bearer tokens, and shared secrets in service-to-service communication.
			Instead of passing a static string, each machine proves its identity with a cryptographic signature generated by a
			private key that never leaves the device.
		</p>
		<p class="mt-3 text-zinc-400">
			Private keys are protected by the OS keychain, TPM 2.0, or — on cloud VMs without hardware storage —
			encrypted with Argon2id. The signing happens on the device; only a 64-byte signature crosses the wire.
		</p>
	</section>

	<section class="py-8">
		<h2 id="problem" class="scroll-mt-20 text-xl font-semibold text-zinc-50">The problem with static secrets</h2>
		<p class="mt-3 text-zinc-400">
			Almost every backend authenticates other services using static strings stored in <code class="rounded bg-emerald-400/10 px-1.5 py-0.5 text-sm text-emerald-400">.env</code> files,
			environment variables, or secrets managers. The model has a fundamental flaw: <strong class="text-zinc-300">the secret IS the identity</strong>.
			Anyone who has the string is authenticated. There is no way to prove <em>which machine</em> used it, whether it was copied, or where it's been.
		</p>
		<div class="mt-6 space-y-3">
			<div class="rounded-lg border-l-2 border-red-400/40 bg-red-950/20 px-4 py-3">
				<p class="text-sm font-medium text-red-300">GitHub secret scanning detected over 1 million leaked secrets in public repos in 2024 alone.</p>
				<p class="mt-1 text-xs text-zinc-500">Every year, major breaches trace back to leaked credentials. The leak vectors are mundane: .env files committed to git, secrets printed to logs, Docker images pushed to public registries, CI/CD build logs.</p>
			</div>
		</div>
		<p class="mt-4 text-zinc-400">
			Rotation is painful, there's no per-machine identity, and secrets managers only move the problem — the secret still
			exists as a copyable string, still needs its own authentication, and still adds latency on every cold start.
		</p>
	</section>

	<section class="py-8">
		<h2 id="how-different" class="scroll-mt-20 text-xl font-semibold text-zinc-50">How amesh is different</h2>
		<div class="mt-4 space-y-3">
			<div class="rounded-lg border border-zinc-800 p-4" style="background:#0C0C0E">
				<h3 class="text-sm font-semibold text-emerald-400">No string to leak</h3>
				<p class="mt-1 text-sm text-zinc-400">The private key is generated on the device and never exported. You can commit your entire codebase to a public repo and nothing is compromised.</p>
			</div>
			<div class="rounded-lg border border-zinc-800 p-4" style="background:#0C0C0E">
				<h3 class="text-sm font-semibold text-emerald-400">No rotation</h3>
				<p class="mt-1 text-sm text-zinc-400">Device keys don't expire. If a device is compromised, revoke it instantly with <code class="font-mono text-xs">amesh revoke</code> — only that device loses access.</p>
			</div>
			<div class="rounded-lg border border-zinc-800 p-4" style="background:#0C0C0E">
				<h3 class="text-sm font-semibold text-emerald-400">Per-machine identity</h3>
				<p class="mt-1 text-sm text-zinc-400">Every request arrives with a verified device ID. You know exactly which machine sent it, when, and with what payload. Per-device audit trail comes for free.</p>
			</div>
			<div class="rounded-lg border border-zinc-800 p-4" style="background:#0C0C0E">
				<h3 class="text-sm font-semibold text-emerald-400">Cryptographic proof of origin</h3>
				<p class="mt-1 text-sm text-zinc-400">Each request is signed with a key bound to the device. The signature is non-repudiable — the device can't deny it sent the request, and no other device could have produced the same signature.</p>
			</div>
		</div>
	</section>

	<section class="py-8">
		<h2 id="philosophy" class="scroll-mt-20 text-xl font-semibold text-zinc-50">Design philosophy</h2>
		<ul class="mt-3 space-y-2 text-zinc-400">
			<li class="flex gap-2"><span class="text-emerald-400">▸</span> <span><strong class="text-zinc-300">Private keys never leave the device.</strong> The KeyStore interface takes a message and returns a signature — the key itself is never exposed to application code.</span></li>
			<li class="flex gap-2"><span class="text-emerald-400">▸</span> <span><strong class="text-zinc-300">Hardware-first, graceful fallback.</strong> Secure Enclave on Apple Silicon, TPM 2.0 on Linux, macOS Keychain as a second tier, encrypted file (Argon2id) only on cloud VMs where hardware isn't available.</span></li>
			<li class="flex gap-2"><span class="text-emerald-400">▸</span> <span><strong class="text-zinc-300">One-way trust.</strong> Controllers authenticate TO targets, never the reverse. A compromised server cannot call back to your laptop.</span></li>
			<li class="flex gap-2"><span class="text-emerald-400">▸</span> <span><strong class="text-zinc-300">Open cryptography only.</strong> Built on audited <code class="font-mono text-xs">@noble/curves</code>, <code class="font-mono text-xs">@noble/hashes</code>, and <code class="font-mono text-xs">@noble/ciphers</code>. P-256 ECDSA, SHA-256 HMAC, ChaCha20-Poly1305.</span></li>
			<li class="flex gap-2"><span class="text-emerald-400">▸</span> <span><strong class="text-zinc-300">Stateless relay.</strong> The pairing relay holds no persistent state — it just brokers a WebSocket handshake. You can shut it down after pairing.</span></li>
		</ul>
	</section>

	<section class="py-8">
		<h2 id="not-for" class="scroll-mt-20 text-xl font-semibold text-zinc-50">What amesh is not for</h2>
		<p class="mt-3 text-zinc-400">amesh authenticates <em>machines</em>, not humans. If you need:</p>
		<ul class="mt-3 space-y-1.5 text-zinc-400">
			<li>• <strong class="text-zinc-300">User login</strong> — use OAuth, WebAuthn, or passkeys</li>
			<li>• <strong class="text-zinc-300">Ephemeral compute</strong> (serverless functions, short-lived containers) — device-bound identity only makes sense on machines with stable hardware or persistent filesystems</li>
			<li>• <strong class="text-zinc-300">Browser-to-server auth</strong> — browsers don't have device identities</li>
		</ul>
		<p class="mt-4 text-zinc-400">
			amesh shines for service-to-service auth on long-running machines: API servers, microservices, cron job hosts,
			developer laptops, CI runners with persistent state, and edge devices.
		</p>
	</section>

	<PrevNextNav {prev} {next} />
	<RelatedContent links={relatedLinks} />
</div>
